/**
 * This file is auto-generated by Supabase CLI.
 * Run `supabase gen types typescript --local > types/database.types.ts` to regenerate.
 * 
 * For production: `supabase gen types typescript --project-id your-project-id > types/database.types.ts`
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type OrderStatus = 'draft' | 'pending' | 'approved' | 'rejected' | 'completed' | 'cancelled'
export type PaymentStatus = 'pending' | 'paid' | 'overdue' | 'cancelled'
export type PaymentMethod = 'cash' | 'direct_debit' | 'online'
export type DeliveryStatus = 'pending' | 'assigned' | 'in_transit' | 'delivered' | 'returned'
export type UserRole = 'admin' | 'store_owner' | 'driver' | 'kitchen_staff'

export interface Database {
  public: {
    Tables: {
      stores: {
        Row: {
          id: string
          name: string
          email: string
          phone: string | null
          address: string | null
          city: string | null
          state: string | null
          zip_code: string | null
          credit_limit: number
          current_balance: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          email: string
          phone?: string | null
          address?: string | null
          city?: string | null
          state?: string | null
          zip_code?: string | null
          credit_limit?: number
          current_balance?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          email?: string
          phone?: string | null
          address?: string | null
          city?: string | null
          state?: string | null
          zip_code?: string | null
          credit_limit?: number
          current_balance?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      products: {
        Row: {
          id: string
          name: string
          description: string | null
          sku: string
          price: number
          cost: number | null
          unit: string
          category: string | null
          is_active: boolean
          min_stock_level: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          sku: string
          price: number
          cost?: number | null
          unit?: string
          category?: string | null
          is_active?: boolean
          min_stock_level?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          sku?: string
          price?: number
          cost?: number | null
          unit?: string
          category?: string | null
          is_active?: boolean
          min_stock_level?: number
          created_at?: string
          updated_at?: string
        }
      }
      orders: {
        Row: {
          id: string
          order_number: string
          store_id: string
          status: OrderStatus
          total_amount: number
          discount_amount: number
          final_amount: number
          notes: string | null
          created_by: string | null
          approved_by: string | null
          approved_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_number: string
          store_id: string
          status?: OrderStatus
          total_amount?: number
          discount_amount?: number
          final_amount?: number
          notes?: string | null
          created_by?: string | null
          approved_by?: string | null
          approved_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_number?: string
          store_id?: string
          status?: OrderStatus
          total_amount?: number
          discount_amount?: number
          final_amount?: number
          notes?: string | null
          created_by?: string | null
          approved_by?: string | null
          approved_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      order_items: {
        Row: {
          id: string
          order_id: string
          product_id: string
          quantity: number
          unit_price: number
          total_price: number
          created_at: string
        }
        Insert: {
          id?: string
          order_id: string
          product_id: string
          quantity: number
          unit_price: number
          total_price: number
          created_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          product_id?: string
          quantity?: number
          unit_price?: number
          total_price?: number
          created_at?: string
        }
      }
      store_stock: {
        Row: {
          id: string
          store_id: string
          product_id: string
          current_stock: number
          last_updated: string
          updated_by: string | null
        }
        Insert: {
          id?: string
          store_id: string
          product_id: string
          current_stock?: number
          last_updated?: string
          updated_by?: string | null
        }
        Update: {
          id?: string
          store_id?: string
          product_id?: string
          current_stock?: number
          last_updated?: string
          updated_by?: string | null
        }
      }
      deliveries: {
        Row: {
          id: string
          order_id: string
          driver_id: string | null
          status: DeliveryStatus
          scheduled_date: string | null
          delivered_at: string | null
          temperature_reading: number | null
          proof_of_delivery_url: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_id: string
          driver_id?: string | null
          status?: DeliveryStatus
          scheduled_date?: string | null
          delivered_at?: string | null
          temperature_reading?: number | null
          proof_of_delivery_url?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          driver_id?: string | null
          status?: DeliveryStatus
          scheduled_date?: string | null
          delivered_at?: string | null
          temperature_reading?: number | null
          proof_of_delivery_url?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      returns: {
        Row: {
          id: string
          delivery_id: string
          product_id: string
          quantity: number
          reason: string
          returned_at: string
          created_at: string
        }
        Insert: {
          id?: string
          delivery_id: string
          product_id: string
          quantity: number
          reason?: string
          returned_at?: string
          created_at?: string
        }
        Update: {
          id?: string
          delivery_id?: string
          product_id?: string
          quantity?: number
          reason?: string
          returned_at?: string
          created_at?: string
        }
      }
      payments: {
        Row: {
          id: string
          order_id: string
          amount: number
          payment_method: PaymentMethod
          payment_status: PaymentStatus
          transaction_id: string | null
          payment_date: string | null
          proof_url: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_id: string
          amount: number
          payment_method: PaymentMethod
          payment_status?: PaymentStatus
          transaction_id?: string | null
          payment_date?: string | null
          proof_url?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          amount?: number
          payment_method?: PaymentMethod
          payment_status?: PaymentStatus
          transaction_id?: string | null
          payment_date?: string | null
          proof_url?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      invoices: {
        Row: {
          id: string
          invoice_number: string
          order_id: string
          store_id: string
          subtotal: number
          discount_amount: number
          return_amount: number
          total_amount: number
          due_date: string | null
          payment_status: PaymentStatus
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          invoice_number: string
          order_id: string
          store_id: string
          subtotal: number
          discount_amount?: number
          return_amount?: number
          total_amount: number
          due_date?: string | null
          payment_status?: PaymentStatus
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          invoice_number?: string
          order_id?: string
          store_id?: string
          subtotal?: number
          discount_amount?: number
          return_amount?: number
          total_amount?: number
          due_date?: string | null
          payment_status?: PaymentStatus
          created_at?: string
          updated_at?: string
        }
      }
      user_profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          role: UserRole
          store_id: string | null
          phone: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          role: UserRole
          store_id?: string | null
          phone?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          role?: UserRole
          store_id?: string | null
          phone?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      kitchen_sheets: {
        Row: {
          id: string
          order_id: string
          prepared_at: string | null
          completed_at: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_id: string
          prepared_at?: string | null
          completed_at?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          prepared_at?: string | null
          completed_at?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      kitchen_sheet_items: {
        Row: {
          id: string
          kitchen_sheet_id: string
          product_id: string
          quantity: number
          batch_number: string | null
          expiry_date: string | null
          prepared: boolean
          created_at: string
        }
        Insert: {
          id?: string
          kitchen_sheet_id: string
          product_id: string
          quantity: number
          batch_number?: string | null
          expiry_date?: string | null
          prepared?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          kitchen_sheet_id?: string
          product_id?: string
          quantity?: number
          batch_number?: string | null
          expiry_date?: string | null
          prepared?: boolean
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      order_status: OrderStatus
      payment_status: PaymentStatus
      payment_method: PaymentMethod
      delivery_status: DeliveryStatus
      user_role: UserRole
    }
  }
}

